Docs/schemas
sonr-io/docs pull request #3
Opened 2022-08-12 19:09 UTC by joshLong145

- Addition of Schema Documentation With New Heading structure.

2022-08-12 19:33 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> ----
???

2022-08-12 19:33 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +Schemas are implemented on the `IPLD Object Model` which allows developers to register specific application data schemas. see [here](https://ipld.io/docs/schemas)
Captialize see

2022-08-12 19:35 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +  "image": "ipfs://QmZWD55U2SDp9uQ5m8hS77EdavpnatTcBMDAkEEKnPWGbn",
would this not be a link?

2022-08-16 18:28 UTC, ntindle commented
@ma-sonr plz review this

2022-08-16 18:33 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +Schemas are implemented on the `IPLD Object Model` which allows developers to register specific application data schemas. see [here](https://ipld.io/docs/schemas)
The hypertext should be descriptive instead of 'here', something like
See [**IPLD Schema documentation**](https://ipld.io/docs/schemas)

2022-08-16 18:38 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +The following is an example schema for an `NFT`
I'd clarify that this is a schema where all of the input types are strings, which is type #7 as specified above 

Something like: The following is an example schema for an `NFT`, which is defined by three String (IPLD field type #7) fields

2022-08-16 18:40 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +  "image": "ipfs://QmZWD55U2SDp9uQ5m8hS77EdavpnatTcBMDAkEEKnPWGbn",
You should also clarify that in this example, image is also a string and represent the location of the image (or something along those lines).

2022-08-16 18:42 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +Allows for Schemas to be depricated. Depricated schemas are still accessible but will allow schemas developers to indicate it is no longer supported.
Deprecate / Deprecated *

2022-08-16 18:50 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +Each field reperesents an `ipld` see [here](https://ipld.io/docs/schemas/features/typekinds/)
Which list is this mapping to exactly? The list shown at this link if a bit different than the list we are using below.

2022-08-16 18:55 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +  "image": "ipfs://QmZWD55U2SDp9uQ5m8hS77EdavpnatTcBMDAkEEKnPWGbn",
I'd suggest adding a realistic description / name. Creating a scenario makes the examples more understandable and sticky. 

Think through a specific scenario in which you might actually want the above schema (NFT with description, image, and name, all of which a strings) and use that to paint the picture of the example

2022-08-16 18:56 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +Each field reperesents an `ipld` see [here](https://ipld.io/docs/schemas/features/typekinds/)
See comment below

2022-08-23 04:38 UTC, ma-sonr requested changes
Comments around clarity as it relates to Types, cid, and did

2022-08-23 04:38 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +  "createdAt": 1661220968,
Either use "timestamp" for both or "createdAt" for both

2022-08-23 04:38 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
>  ```go
It seems your removed the enum here but then use it in the example to follow

2022-08-23 04:38 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +```json
There needs to be an enum defined above for the below JSON examples to make sense

2022-08-23 04:38 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +```json
imo the enum is not helpful, why not just use the type directly> Like 

{
  "description": String, 
  "image": String, 
  "name": String,
  "attributes": List 
}

The enum numbering and ordering is arbitrary and subject to change, whereas the specific types don't change. Why should a developer have to remember that 0 refers to a List type and 4 to a String?

2022-08-23 04:38 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +The result of uploading an object will be a `cid` and `did`
I would reframe this to highlight the relevance of the cid and did to the object, rather than just mention that they are created. Something like: 

"Once an object is uploaded, both a 'cid' and 'did' are produced, which allow the object to be _____."

2022-08-23 19:43 UTC, ma-sonr commented on docs/src/highway/modules/schemas.md
> +```json
@ntindle

2022-08-23 20:54 UTC, joshLong145 commented on docs/src/highway/modules/schemas.md
> +```json
my idea was to keep the docs accurate to the code but in realty these are all enumerated and available to the developer from our type libraries. ill make that change

2022-09-01 02:25 UTC, ntindle reviewed
Are there multiple same files?

2022-09-01 02:25 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +A `Schema Definition` is used to describe an application Schema that will be stored for later assertion against. the provided `Schema Definition` is then used to Derive both the `WhatIs` and `Schema
Capitalize the start of the sentence starting with `the`

2022-09-01 02:25 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +A `ScehamReference` is used to store information about a `ScehmaDefinition` on our blockchain. This is stored within what is called a `WhatIs` record. Which holds infromation describing the registere
“Which holds information …” is a sentence fragment and should be combined into the sentence preceding it.

2022-09-01 02:25 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +A `Schema Reference` is used to repersent off chain information related to the `Schema` being registered. This is held within the `WhatIs` record that is written to the chain. A `Schema Reference` he
“Which is…” is a sentence fragment and should be combined into the sentence precededign it

2022-09-01 02:25 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +Register's a new type definition for a given application. this type defention is then asserted against when uploading content
Definition

capitalize this

2022-09-01 02:25 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +Allows for Schemas to be depricated. Depricated schemas are still accessible but will allow developers to indicate it is no longer supported.
Deprecated

2022-09-01 02:25 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +- `Creator` The Account Address Singing this message
Signing

2022-09-01 02:25 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +For cases it is dersired to lookup a Schema Definition for verifying on an uploaded object.
Desired

2022-09-01 02:25 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +For cases where applications need to verify existing data, or verify a schema belongs to a certain `Creator`. `QueryWhatIs` should be used over `QuerySchema` when only verification of the data is nee
. -> ,

2022-09-01 02:25 UTC, ntindle commented on docs/src/highway/modules/schemas.md
> +A CID can be tracked as an item within a bucket. Which are used to relate pieces of content and query them based on their Schema
Don’t start sentences with “which” generally. Sometimes it’s okay if it’s a choice based thing but which as a off-setter should never begin a sentence

2022-09-01 02:25 UTC, ntindle commented on docs/src/motor-sdk/data/data-schemas.md
> +---
Is this the exact same file?

2022-09-02 00:25 UTC, merged